### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by brindakv** [Fluorescence-Tools/LabelLib#1]
Could you please provide documentation and some test cases so that I can try using the tool?

**Comment by mdimura** [comment]
Thank you for your request! Yes, I added a Pymol usage example, which you can find in the [README.md](https://github.com/Fluorescence-Tools/LabelLib#pymol). There are also some more test cases available: [testFlexLabel.cxx](https://github.com/Fluorescence-Tools/LabelLib/blob/master/FlexLabel/test/testFlexLabel.cxx) and [usage.py](https://github.com/Fluorescence-Tools/LabelLib/blob/master/FlexLabel/python/usage.py)
