### ISSUE TITLE
Function that calculates for a given Grid3D a list of cartesian points

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/LabelLib#10]
This is a very trivial enhancement suggestion, that however may improve the performance of LabelLib, particularly when Python is used

Right now, to create a list of the valid labeling positions, we loop over the density array.

```python
  MP=np.array([0.0,0.0,0.0])
  vol=0.0
  iat = 0
  for iz in range(nz):
    for iy in range(ny):
      for ix in range(nx):
        val = g[ix, iy, iz]
        if val <= 0.0:
          continue
```

It would be more efficient, if this loop would be implemented in C/C++, meaning if there would be a function that converts a Grid3D object to a list of (Cartesian) points optionally with density values.

**Comment by mdimura** [comment]
I've implemented the missing bindings. Now one can do this:
```
  points = av.points()
  for p in points.T:
    x, y, z, w = p
```

**Comment by tpeulen** [comment]
Great!!!
