### ISSUE TITLE
Contribute LabelLib to conda forge

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/LabelLib#13]
We should consider to add LabelLib to conda forge. This way, LabelLib could be used with less hassle by more people. I already created a conda-recipe that builds on macOS, Windows, and Linux.

https://github.com/Fluorescence-Tools/conda-recipes/

Only Python 2.7 is a bit tricky to build on Windows because stdint.h is missing in VS 2008 (the standard compiler for Python 2.7 on Windows). If it is okay to drop python 2.7 support for conda-forge contributing LabelLib to conda-forge should be straightforward.

https://conda-forge.org/docs/maintainer/adding_pkgs.html#dev-contribute-pkgs

The question is if we fell that LabelLib is mature enough to be submitted to conda-forge.

**Comment by tpeulen** [comment]
If we consider adding LabelLib to conda-forge, LabelLib should be built from tarballs (see: 
https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=packaging%20license#tarballs-no-repos)

**Comment by mdimura** [comment]
The issue can be discussed in #19
