### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/LabelLib#15]
LabelLib reached a level of maturity where others may start to use it, either by incorporating its code or by linking against it. Still, we may want to change the library. Hence, I suggest to use for future releases [semantic versioning](https://semver.org/). This way, others can easily track if a new release breaks their code.
In semantic versioning:

Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards compatible manner, and
    PATCH version when you make backwards compatible bug fixes.

**Comment by mdimura** [comment]
We know, that current API will be fully changed from stl+Eigen to Eigen/numpy. Current version will be obsolete. If we will have to do a change like that again, we will probably need the semantic versioning. I suggest to revisit this question at that point.
