### ISSUE TITLE
pip install LabelLib==2019.10.9 install version from 2018

### ISSUE THREAD

**Issue by ChristianGebhardt** [Fluorescence-Tools/LabelLib#18]
Hi,
I am using the LabelLib package in my code with the new feature of using the points from the AV cloud (av.points()), which was added to the 2019 version of LabelLib (https://github.com/Fluorescence-Tools/LabelLib/issues/10)

However, I cannot install the new version via pip on Windows: The command `pip  install LabelLib==2019.10.9`  still installs the old version from 2018. It only works with conda `conda install -c tpeulen labellib`.

Since I want to add LabelLib to the dependencies of a package, it should work with pip as well. Otherwise it will install the wrong version of LabelLib.

I have seen that the tar.gz file is not provided for the latest versions. But even for the version 2019.3.17, pip installs the 2018.12.14 instead. Do you know, where this might come from? Can you update PyPI to support Windows installations of the latest version. Thank you!

**Comment by mdimura** [comment]
Thank you for your report! I've uploaded the source distribution for the version 2019.10.9 to pypi. I will also prepare the windows wheel file later. Version 2019.3.17 does not have the windows version of the .whl 2019.10.9 either. Probably this is why it does not get installed.

**Comment by ChristianGebhardt** [comment]
Thanks for the quick response and your help. I tried to install it again, but it failed. (The file size is also just 400 kB instead of 3 MB for the older versions --> is this expected?).

It raised an error in the setup.py in the line:
`out = check_output(['git', 'show', '-s', '--format=%cd', '--date=short'])`

![grafik](https://user-images.githubusercontent.com/19477444/94154121-dc620580-fe7d-11ea-81d8-f265c48439b9.png)

**Comment by mdimura** [comment]
I've built and uploaded the 2019.10.9 version of the windows wheel for python 3.8 to PyPi, that should work now.

**Comment by ChristianGebhardt** [comment]
I tried it and it it is working. Thanks!
