### ISSUE TITLE
pubby-flat issue MacOS

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/LabelLib#2]
LabelLib does not compile on MacOS. I nailed down the problem to the newly introduced library pubby-flat. In the file 'flat_map.hpp' std::void_t is used. This only became a part of the std library in C++17, which is not supported by clang / LLVM - the standard MacOS compiler.

take a look at line 184 flat_map.hpp

**Comment by tpeulen** [comment]
the issue mainly that c++17 is not supported by visual studio older than 2017. to work correctly python libraries for Python 2.7 should be compiled with VC 9. hence, for compatibility advanced c++17 should not be used.

**Comment by mdimura** [comment]
If i get it right, VC9 does not support even c++11. How did we compile it before? C++14 requirement was there from the [very first commit](https://github.com/Fluorescence-Tools/LabelLib/blob/b0881dc977906abb16a4e44af2415b9b1fed48b0/FlexLabel/CMakeLists.txt#L4).
What is the version of clang on macOS? Clang 5 and later implement all the features of the ISO C++ 2017 standard, and [clang 3.8 seems to support many c++17 features as well](https://en.cppreference.com/w/cpp/compiler_support). It seems, it is possible to use mingw as an alternative for VC9 on python 2.7, so I could try to make it work with c++17 on windows. But it only makes sense if it will be possible to compile with c++17 on MacOS as well.

**Comment by tpeulen** [comment]
It seems that some imports were simply missing. To get the new 2018.11.30 version compiled on Windows I needed to add additional imports to FlexLabel.cxx

FlexLabel.cxx

Error: accumulate not known
Line: 543
Fix: #inculde <numeric> header

Error: keyword not known
Line: 550
Fix: #include <ciso646>
