### ISSUE TITLE
LabelLib fails 

### ISSUE THREAD

**Issue by Mattyboi123** [Fluorescence-Tools/LabelLib#22]
Hello,

I have had a persistent problem with LabelLib. Upon running the code in pymol

`_genAV('ins_sub_2_test0', '/ins_sub_2_test0//F/60/CB', allowed_sphere_radius=1.5, linker_diameter=4.5, linker_length=20.5)_`

I get the following error
```
Traceback (most recent call last):
  File "C:\Users\fbsmawadmin\Anaconda3_\Lib\site-packages\LabelLib\FlexLabel\python\LabelLib_pymol.py", line 40, in genAV
    av1=ll.dyeDensityAV1(xyzRT.T,source,linker_length, linker_diameter, dye_radius, disc_step)
AttributeError: module 'LabelLib' has no attribute 'dyeDensityAV1'
```

might there be some python script or a line missing that defines the attribute dyeDensityAV1 ??

**Comment by mdimura** [comment]
I could not reproduce the error. Could you please try and run the example from the readme?
```
cmd.do('run ./LabelLib/FlexLabel/python/LabelLib_pymol.py')
cmd.fetch('1BNA')
genAV('1BNA', '/1BNA/B/B/19/C5', allowed_sphere_radius=1.5)
```
Which Pymol & LabelLib versions do you have?

**Comment by Mattyboi123** [comment]
It was happening with one from late 2019 and still behaves the same way
with the 2020_10_05 version. That version didn't fully install through pip,
just th dist info folder so I downloaded the zip archive and copied the
folder into my site packages directory.. might that be part of the problem?

**Comment by mdimura** [comment]
Yes, copying the sources to the site-packages directory will not do it, unfortunately. What was the problem with pip? What's your OS/env?

**Comment by Mattyboi123** [comment]
The package folder was not installed into my site packages folder,conly the
dist info folder was installed

**Comment by mdimura** [comment]
What's your OS/env? Could you please provide the installation log?
