### ISSUE TITLE
Switch from LGPL to less copyleft MPL

### ISSUE THREAD

**Issue by mdimura** [Fluorescence-Tools/LabelLib#7]
Unlike LGPL, MPL does not require that derived closed software is linked dynamically. Otherwise they are similar. This will allow to make LabelLib header-only.
http://www.mozilla.org/MPL/2.0/FAQ.html

**Comment by tpeulen** [comment]
I think the MPL is a great license for LabelLib (less viral than LGPL). Other libraries may benefit from LabelLib at the same time changes to LabelLib have to be under the MPL. Using the MPL is a great suggestion.

-  MPL: The copyleft applies to any files containing MPLed code.
-  LGPL: The copyleft applies to any library based on LGPLed code.
-  GPL: The copyleft applies to all software based on GPLed code. 

I fully agree with relicensing LabelLib to MPL 2.0


For that the header from Exhibit A of the license should be added to each source code file.

```

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

```

**Comment by mdimura** [comment]
I didn't want to change every file and keep track of them, so went for the "lite" option:

> If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

Hope it's OK, but I don't mind going the "hard" way for a disclaimer in every file, if you prefer.

**Comment by tpeulen** [comment]
I'm not a license expert. If they state that it's okay to use a single LICENSE file. That's fine with me.
